public class Restaurant {
    @AuraEnabled
    public String id;
    @AuraEnabled
    public String restaurantName;
    @AuraEnabled
    public String address;
    @AuraEnabled
    public String zipCode;
    @AuraEnabled
    public String phone;
    @AuraEnabled
    public String website;
    @AuraEnabled
    public String latitude;
    @AuraEnabled
    public String longitude;
    @AuraEnabled
    public String stateName;
}
